version: '3'
services:
 app:
  ports:
   - "80:80"
  build: ./docker/app
  volumes:
   - ./src:/var/www/html
  privileged: true
  tty: true

 db:
  build: ./docker/db
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test_db
   MYSQL_USER: test_user
   MYSQL_PASSWORD: test_pass
   TZ: 'Asia/Tokyo'
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  volumes:
   - ./init:/docker-entrypoint-initdb.d
   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   - db-store:/var/lib/mysql
  ports:
   - 3306:3306
  tty: true

 php-my-admin:
  image: phpmyadmin/phpmyadmin
  links:
   - db
  ports:
   - "89:80"
  environment:
   MYSQL_USERNAME: test_user
   MYSQL_ROOT_PASSWORD: test_pass
   PMA_HOST: db
   PMA_PORT: 3306

 redis:
  image: "redis:latest"
  ports:
   - "6379:6379"
  volumes:
   - "./data/redis:/data"
  tty: true

 
volumes: 
 db-store: